export const FAILURE_TYPES = {
  DEAD: 'dead',
  STUCK_ON: 'stuck_on',
  LOW_SENSITIVITY: 'low_sensitivity',
  DELAYED_OFF: 'delayed_off',
}

export const FAILURE_LABELS = {
  [FAILURE_TYPES.DEAD]: '灯泡不亮',
  [FAILURE_TYPES.STUCK_ON]: '常亮不灭',
  [FAILURE_TYPES.LOW_SENSITIVITY]: '灵敏度低',
  [FAILURE_TYPES.DELAYED_OFF]: '延迟熄灭',
}

export const FAILURE_HINTS = {
  [FAILURE_TYPES.DEAD]: '拖拽备用灯泡到灯座更换',
  [FAILURE_TYPES.STUCK_ON]: '点击电闸按钮断电',
  [FAILURE_TYPES.LOW_SENSITIVITY]: '快速点击灯座模拟跺脚！',
  [FAILURE_TYPES.DELAYED_OFF]: '调节滑动条到绿色正常区间',
}

export const GAME_CONFIG = {
  TOTAL_FLOORS: 6,
  GAME_DURATION: 60,
  POINTS_PER_REPAIR: 100,
  PENALTY_WRONG_ACTION: -30,
  BONUS_ALL_FIXED: 200,
  PENALTY_TIMEOUT: -50,
}

export const DIFFICULTY = {
  LOW_SENSITIVITY_CLICKS: 8,
  DELAYED_OFF_TARGET_MIN: 3,
  DELAYED_OFF_TARGET_MAX: 5,
  SLIDER_MIN: 1,
  SLIDER_MAX: 10,
  RAINY_MULTIPLIER: 1.5,
}
